In [1]:
import pandas as pd
import numpy as np

In [4]:
column_names = ['Attack', 'Defense', 'Speed', 'Generation']
print(column_names)

['Attack', 'Defense', 'Speed', 'Generation']


In [3]:
pokemon_data = np.genfromtxt('file.csv', delimiter=',', dtype='float', usecols=[0,1,2,3])

In [4]:
pokemon_data

array([[ nan,  49.,  45.,   3.],
       [ 62.,  63.,  nan,   1.],
       [ 82.,  83.,  80.,   1.],
       [100., 123.,  80.,   1.],
       [ 52.,  43.,  65.,   2.],
       [ 64.,  58.,  nan,   1.],
       [ 84.,  78., 100.,   2.],
       [130., 111., 100.,   1.],
       [104.,  78., 100.,   3.],
       [ 48.,  65.,  43.,   1.],
       [ 63.,  80.,  58.,   2.],
       [ 83., 100.,  78.,   1.],
       [103., 120.,  78.,   1.],
       [ 30.,  35.,  nan,   1.],
       [ 20.,  55.,  30.,   3.],
       [ 45.,  50.,  70.,   1.]])

In [6]:
a = [1,23,4,5,6,7,8]
a[:]

[1, 23, 4, 5, 6, 7, 8]

In [7]:
# Look at the 'speed' column
pokemon_data[:,2]

array([ 45.,  nan,  80.,  80.,  65.,  nan, 100., 100., 100.,  43.,  58.,
        78.,  78.,  nan,  30.,  70.])

###  1) Lets check null/nan/missing value

In [9]:
np.isnan(pokemon_data[:,2])

array([False,  True, False, False, False,  True, False, False, False,
       False, False, False, False,  True, False, False])

In [14]:
pokemon_data[:,2]

array([ 45.,  nan,  80.,  80.,  65.,  nan, 100., 100., 100.,  43.,  58.,
        78.,  78.,  nan,  30.,  70.])

In [17]:
np.where([True, False, True])

(array([0, 2], dtype=int64),)

In [25]:
x = [1,np.nan,3,np.nan,5,np.nan]
a = np.isnan([100,np.nan,300,np.nan,566,np.nan])
print(a)
b = np.where(np.isnan([1,np.nan,3,np.nan,5,np.nan]))
b


[False  True False  True False  True]


(array([1, 3, 5], dtype=int64),)

In [19]:


# Solution
print("Number of missing values: ", np.isnan(pokemon_data[:, 2]).sum())
print("Position of missing values: ", np.where(np.isnan(pokemon_data[:, 2])))


#explaining
np.isnan([1,2,3,np.nan])

Number of missing values:  3
Position of missing values:  (array([ 1,  5, 13], dtype=int64),)


array([False, False, False,  True])

### 2) How to filter a numpy array based on two or more conditions?

In [20]:
print("Names of the columns of pokemon data : ", column_names)
print(pokemon_data)

Names of the columns of pokemon data :  ['Attack', 'Defense', 'Speed', 'Generation']
[[ nan  49.  45.   3.]
 [ 62.  63.  nan   1.]
 [ 82.  83.  80.   1.]
 [100. 123.  80.   1.]
 [ 52.  43.  65.   2.]
 [ 64.  58.  nan   1.]
 [ 84.  78. 100.   2.]
 [130. 111. 100.   1.]
 [104.  78. 100.   3.]
 [ 48.  65.  43.   1.]
 [ 63.  80.  58.   2.]
 [ 83. 100.  78.   1.]
 [103. 120.  78.   1.]
 [ 30.  35.  nan   1.]
 [ 20.  55.  30.   3.]
 [ 45.  50.  70.   1.]]


In [10]:
# Solution
condition = (pokemon_data[:, 0] > 50) & (pokemon_data[:, 1] > 50)
print(condition)
pokemon_data[condition]

[False  True  True  True False  True  True  True  True False  True  True
  True False False False]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in greater
  


array([[ 62.,  63.,  nan,   1.],
       [ 82.,  83.,  80.,   1.],
       [100., 123.,  80.,   1.],
       [ 64.,  58.,  nan,   1.],
       [ 84.,  78., 100.,   2.],
       [130., 111., 100.,   1.],
       [104.,  78., 100.,   3.],
       [ 63.,  80.,  58.,   2.],
       [ 83., 100.,  78.,   1.],
       [103., 120.,  78.,   1.]])

### 3) How to drop rows that contain a missing value from a numpy array?

In [8]:
pokemon_data

array([[ nan,  49.,  45.,   3.],
       [ 62.,  63.,  nan,   1.],
       [ 82.,  83.,  80.,   1.],
       [100., 123.,  80.,   1.],
       [ 52.,  43.,  65.,   2.],
       [ 64.,  58.,  nan,   1.],
       [ 84.,  78., 100.,   2.],
       [130., 111., 100.,   1.],
       [104.,  78., 100.,   3.],
       [ 48.,  65.,  43.,   1.],
       [ 63.,  80.,  58.,   2.],
       [ 83., 100.,  78.,   1.],
       [103., 120.,  78.,   1.],
       [ 30.,  35.,  nan,   1.],
       [ 20.,  55.,  30.,   3.],
       [ 45.,  50.,  70.,   1.]])

In [31]:
np.isnan([ 4,  55]).any()

False

In [22]:
# Note : there is no direct function for this in numpy
# Hence, Pandas = for data read, data cleaning, data manipulation, data saving 
# and numpy = scientific calculation
mask = []
for row in pokemon_data:
    #print("value of each row : ", row)
    #print("value after checking np.isnan() : ", np.isnan(row)) # gives a boolean value on element's place  True = if missing, False = not missing
    #print("value after using np.any() on np.isnan() : ", np.any(np.isnan(row)))
    if np.isnan(row).any():
        mask.append(False)
    else:
        mask.append(True)
    #print(row)
#print(mask)
#np.where(mask)

In [34]:
# Note : there is no direct function for this in numpy
# Hence, Pandas = for data read, data cleaning, data manipulation, data saving 
# and numpy = scientific calculation
mask = []
for row in pokemon_data:
    #print(row)
    checker = np.isnan(row).any()
    if checker:
        mask.append(False)
    else:
        mask.append(True)


In [35]:
mask

[False,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True]

In [23]:
non_null_pokemon_data = pokemon_data[mask]
print(non_null_pokemon_data)

[[ 82.  83.  80.   1.]
 [100. 123.  80.   1.]
 [ 52.  43.  65.   2.]
 [ 84.  78. 100.   2.]
 [130. 111. 100.   1.]
 [104.  78. 100.   3.]
 [ 48.  65.  43.   1.]
 [ 63.  80.  58.   2.]
 [ 83. 100.  78.   1.]
 [103. 120.  78.   1.]
 [ 20.  55.  30.   3.]
 [ 45.  50.  70.   1.]]


In [36]:
dummy = np.array([2,4,6,8,10])
mask = [True, False, True, False, True]
dummy[mask]

array([ 2,  6, 10])

### 4) How to find the correlation between two columns of a numpy array?

In [25]:
np.corrcoef(non_null_pokemon_data[:, 0], non_null_pokemon_data[:, 2])

array([[1.        , 0.85846985],
       [0.85846985, 1.        ]])

In [24]:
coeff = np.corrcoef(non_null_pokemon_data[:, 0], non_null_pokemon_data[:, 2])[0,1]
# also show round()
round(coeff,3)


0.858

In [21]:
coeff

0.8584698498875397

In [31]:
a = np.array([1,2,3,np.nan])

In [32]:
a

array([ 1.,  2.,  3., nan])

In [35]:
ind = np.where(np.isnan(a))

In [37]:
a[ind] = 99

In [38]:
a

array([ 1.,  2.,  3., 99.])