In [2]:
import numpy as np

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
import numpy

In [5]:
numpy.array([1,2,3])

array([1, 2, 3])

In [6]:
import numpy as abhishek

In [7]:
abhishek.array([1,2,3])

array([1, 2, 3])

In [15]:
x = [5,1,2]

In [16]:

x.sort()

In [17]:
x

[1, 2, 5]

In [28]:
n = ['zay','Abhishek', 'Dubey']

In [29]:
n.sort()

In [30]:
n

['Abhishek', 'Dubey', 'zay']

In [36]:
#dount#list#sort#

# can we sort list with different data types

# Answer : Basically when you sort any list(means values in a list) you compare them on their values.
# and you cannot compare an 'integet' with 'character'
#ex : you cannot compare 2 and 'Ashish'

# To add to that, you can certainly compare character
#ex:
ch = ['india', 'japan', 'england']
ch.sort()
print(ch)
# output : ['england', 'india', 'japan'] # here the first letters of each country got compared

ch2 = ['india', 'Japan', 'england']
ch2.sort()
print(ch2)
# output : ['Japan', 'england', 'india'] # Here what happened is japan got the preference because it is in upper case

['england', 'india', 'japan']
['Japan', 'england', 'india']


In [41]:
ord('z')

122

In [ ]:

Amul milk
laptop
soap


100 gm





In [49]:
products = ['cadbury Chocolate', 'Amul milk', 'laptop', 'soap']
weights = ['100 gm', '500 ml', '2 KG', '1 pound']
converted_weight = [] # new list to store all the converted weight values
for each_weight in weights:
    val = int(each_weight.split()[0]) # splitting the weight on 'space' and storing first value to val variable
    # have used int(), because after splitting I get string like '100', type casted it to int so that,-
    # - I can do multiplication below
    uom = each_weight.split()[1] #storing unit of measure(uom) to variable uom
    # here is my conversion condition, I googled the conversion between different units to ounce
    if uom.lower() == 'kg':
        val = val*35.27
    if uom.lower() == 'gm':
        val = val*0.035274
    if uom.lower() == 'pound':
        val = val*16
    if uom.lower() == 'ml':
        val = val*0.033814
    converted_weight.append(val) # Note: I have this append() outside of if conditions, - 
    # - having it inside every if condition will serve the purpose but it is just repetetive.

# all the value has been converted, now printing
for prod, old_wght, con_wght in zip(products, weights, converted_weight):
    print("The prod is : {} , the old weight is : {} & the new weight is : {}".format(prod, old_wght, con_wght))

The prod is : cadbury Chocolate , the old weight is : 100 gm & the new weight is : 3.5274
The prod is : Amul milk , the old weight is : 500 ml & the new weight is : 16.907
The prod is : laptop , the old weight is : 2 KG & the new weight is : 70.54
The prod is : soap , the old weight is : 1 pound & the new weight is : 16
